apiVersion: batch/v1
kind: Job
metadata:
  name: zihao-data-download
  namespace: gpu-ml-benchmarks
spec:
  template:
    spec:
      containers:
      - name: data-downloader
        image: ghcr.io/oliverevans96/nautilus-gpu-benchmarks:v1
        command: ["python", "download.py"]
        volumeMounts:
        - mountPath: /data
          name: data-vol
        env:
        - name: DATA_DIR
          value: /data/zihao
        resources:
          limits:
            memory: "8G"
            cpu: "4"
          requests:
            memory: "8G"
            cpu: "4"
      restartPolicy: Never
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: ml-benchmark-datasets
