apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-benchmark-datasets
  namespace: gpu-ml-benchmarks
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Ti
