apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-benchmark-datasets
  namespace: gpu-ml-benchmarks
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
