apiVersion: batch/v1
kind: Job
metadata:
  name: training-data-download
  namespace: gpu-ml-benchmarks
spec:
  template:
    spec:
      containers:
      - name: data-downloader
        image: rclone/rclone
        command: ["rclone", "sync", "--progress", "mlcommons-training-s3:mlcommons-training-wg-s3/", "/data/mlcommons/training/"]
        volumeMounts:
        - mountPath: /data
          name: data-vol
        - name: rclone-config
          mountPath: /config/rclone/rclone.conf
          subPath: rclone.conf
        env:
        - name: RCLONE_CONFIG
          value: /config/rclone/rclone.conf
        resources:
          limits:
            memory: "8G"
            cpu: "4"
          requests:
            memory: "8G"
            cpu: "4"
      restartPolicy: Never
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: ml-benchmark-datasets
      - name: rclone-config
        configMap:
          name: mlcommons-training-s3-creds
